/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.OrdenCompra;

import Controlador.OrdenCompraBL;
import Modelo.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moises
 */
public class frmBusquedaOrdenCompra extends javax.swing.JDialog {

    DefaultTableModel modelo;
    private OrdenCompra ordenCompraSeleccionada;
    private ArrayList<OrdenCompra>lista;
    private OrdenCompraBL logicaNegocioOc;
    /**
     * Creates new form frmBusquedaOrdenCompra
     */
    public OrdenCompra getOrdenCompraSeleccionada() {
        return ordenCompraSeleccionada;
    }

    public void setOrdenCompraSeleccionada(OrdenCompra ordenCompraSeleccionada) {
        this.ordenCompraSeleccionada = ordenCompraSeleccionada;
    }
    public frmBusquedaOrdenCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        logicaNegocioOc = new OrdenCompraBL();
        lista = logicaNegocioOc.devolverLista();
        this.setBackground(Color.yellow);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenCompra = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaOrdenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cantidad Total", "Fecha", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaOrdenCompra);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSeleccionar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscar))
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        try{
            int index = tablaOrdenCompra.getSelectedRow();
            ordenCompraSeleccionada=lista.get(index);
            this.dispose();
        }catch(Exception ex ){
            JOptionPane.showMessageDialog(null, "Seleccione una orden de compra");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            deleteRows();
            Object fila[] = new Object[4];
            ordenCompraSeleccionada=logicaNegocioOc.devolverOrden(Integer.parseInt(txtCodigo.getText()));
            if (ordenCompraSeleccionada!=null){
                fila[0]=ordenCompraSeleccionada.getIdOrdenCompra();
                fila[1]=ordenCompraSeleccionada.getCantidadTotalProducto();
                fila[2]=ordenCompraSeleccionada.getFechaOrdenCompra();
                if (ordenCompraSeleccionada.getEstadoOrdenCompra()==1){
                    fila[3]="No atendida";
                }else{
                    fila[3]="Atendida";
                }

                modelo.addRow(fila);
            }else{
                //lista=null;
                //lista = logicaNegocioOc.devolverLista();
                
                JOptionPane.showMessageDialog(null, "La orden de compra consultada no existe");
                actualizarTabla();
                return;
            }
        }catch(Exception ex){
            //lista=null;
            //lista = logicaNegocioOc.devolverLista();
            
            JOptionPane.showMessageDialog(null, "Ingrese un codigo válido");
            actualizarTabla();
            return;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void deleteRows(){
        int rowCount = modelo.getRowCount();
       
        for (int i=rowCount-1 ; i>=0;i--){
            modelo.removeRow(i);
        }
    }
    private void actualizarTabla(){
        modelo= (DefaultTableModel)tablaOrdenCompra.getModel();
        Object fila[] = new Object[4];

        for (int i=0; i < lista.size();i++){
            fila[0]=lista.get(i).getIdOrdenCompra();
            fila[1]=lista.get(i).getCantidadTotalProducto();
            fila[2]=lista.get(i).getFechaOrdenCompra();
            if (lista.get(i).getEstadoOrdenCompra()==1){
                fila[3]="No atendida";
            }else{
                fila[3]="Atendida";
            }
            
            modelo.addRow(fila);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBusquedaOrdenCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBusquedaOrdenCompra dialog = new frmBusquedaOrdenCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaOrdenCompra;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
