/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.OrdenCompra;

import Vista.frmPrincipal;
import Vista.frmProductosAgotados;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author Moises
 */
public class frmGestionarOrdenCompra extends javax.swing.JInternalFrame {
    private frmPrincipal padre;
    frmProductosAgotados frmProductosAgotados;
    frmOrdenCompra frmOrdenCompra;
    frmBuscarOrdenCompra frmBuscarOrdenCompra;
    
    
    public JDesktopPane getPaneOrdenCompra() {
        return jdpOrdenCompra;
    }

    public void setPaneOrdenCompra(JDesktopPane paneOrdenCompra) {
        this.jdpOrdenCompra = paneOrdenCompra;
    }
    
    public frmProductosAgotados getFrmProductosAgotados() {
        return frmProductosAgotados;
    }

    public void setFrmProductosAgotados(frmProductosAgotados frmProductosAgotados) {
        this.frmProductosAgotados = frmProductosAgotados;
    }
    /**
     * Creates new form frmOrdenCompra
     */
    public frmGestionarOrdenCompra(frmPrincipal padre) {
        initComponents();
        this.padre= padre;
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setLocation(0,0);
        /// Inicializar paneles
        jdpOrdenCompra.removeAll();
        jdpOrdenCompra.repaint();
        frmOrdenCompra = new frmOrdenCompra(this);
        jdpOrdenCompra.add(frmOrdenCompra);
        frmOrdenCompra.show();
    }
    void setColor(JPanel panel){
        panel.setBackground(new Color(30,67,112));
        //85,65,118
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(173, 192, 206));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jdpOrdenCompra = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(54, 63, 69));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(96, 125, 138));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Orden de compra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(877, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdpOrdenCompraLayout = new javax.swing.GroupLayout(jdpOrdenCompra);
        jdpOrdenCompra.setLayout(jdpOrdenCompraLayout);
        jdpOrdenCompraLayout.setHorizontalGroup(
            jdpOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpOrdenCompraLayout.setVerticalGroup(
            jdpOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jdpOrdenCompra, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jdpOrdenCompra))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpOrdenCompra;
    // End of variables declaration//GEN-END:variables
}
