/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.OrdenCompra;


import Controlador.*;

import Modelo.*;
import Vista.frmBusquedaProducto;
import Vista.frmPrincipal;
import Vista.frmProductosAgotados;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
//cardi b , bodak ylllow
/**
 *
 * @author Moises
 */
public class frmOrdenCompra extends javax.swing.JInternalFrame{
    
    private frmProductosAgotados frmProductosAgotados;
    private frmGestionarOrdenCompra padre ;

    private frmBusquedaProducto frmBusquedaProducto;
    private OrdenCompra ordenCompra;
    private Producto p;
    private DefaultTableModel modelo;
    private OrdenCompraBL logicaNegocioOrdenCompra;
    
    /**
     * Creates new form frmOrdenCompra
     */
    public frmOrdenCompra(frmGestionarOrdenCompra padre) {
        initComponents();
        String [] estados = { "No atendida","Atendida"};
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.padre=padre;
        txtCodigo.setEnabled(false);
        txtCodigoProducto.setEnabled(false);
        txtNombreProducto.setEnabled(false);
        ordenCompra = new OrdenCompra();
        cboEstado.setModel(new DefaultComboBoxModel(estados));
        logicaNegocioOrdenCompra = new OrdenCompraBL();
        estado(1);
        //buscarOrdenDeCompra.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleOrdenCompra = new javax.swing.JTable();
        txtFechaOrden = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscarOrdenDeCompra = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 63, 69));
        setBorder(null);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Orden:");

        tablaDetalleOrdenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalleOrdenCompra);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del producto"));

        jLabel3.setText("Código:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Cantidad:");

        btnBuscarProducto.setText("Buscar Producto");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnBuscarProducto)
                                .addGap(62, 62, 62)
                                .addComponent(btnAnadir, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarProducto)
                        .addComponent(btnAnadir)
                        .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuitar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscarOrdenDeCompra.setText("Buscar Orden de compra");
        btnBuscarOrdenDeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarOrdenDeCompraActionPerformed(evt);
            }
        });

        txtTotal.setText("0");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEstado.setText("Modificar");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnRegistrar)
                                .addGap(179, 179, 179)
                                .addComponent(btnGuardar)
                                .addGap(131, 131, 131)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEstado)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFechaOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(80, 80, 80)
                                                .addComponent(jLabel6)
                                                .addGap(37, 37, 37)
                                                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnBuscarOrdenDeCompra))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarOrdenDeCompra))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        try{
           
                Frame f = JOptionPane.getFrameForComponent(this.padre.getPaneOrdenCompra());
                frmBusquedaProducto dialog = new frmBusquedaProducto(f, true);
                dialog.setLocation(0,0);
                dialog.setVisible(true);
                
                
                p=dialog.getProductoSeleccionado();
                
                txtCodigoProducto.setText(String.valueOf(p.getIdProducto()));
                txtNombreProducto.setText(String.valueOf(p.getNombre()));

        }catch(Exception ex){
            //Excepcion
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        estado(1);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarOrdenDeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarOrdenDeCompraActionPerformed
        // TODO add your handling code here:
        try{
            frmBusquedaOrdenCompra fBOC = new frmBusquedaOrdenCompra(JOptionPane.getFrameForComponent(this.padre.getPaneOrdenCompra()),true);
            fBOC.setVisible(true);
            ordenCompra = fBOC.getOrdenCompraSeleccionada();
            txtCodigo.setText(String.valueOf(ordenCompra.getIdOrdenCompra()));
            txtFechaOrden.setDate(ordenCompra.getFechaOrdenCompra());
            txtTotal.setText(String.valueOf(ordenCompra.getCantidadTotalProducto()));
            int i ;
            if ( ordenCompra.getEstadoOrdenCompra()==1)
                i=0;//no atendida
            else
                i=1;//atendida
            cboEstado.setSelectedIndex(i);
            actualizarTabla();
        }catch(Exception ex){
        }
    }//GEN-LAST:event_btnBuscarOrdenDeCompraActionPerformed
    private void actualizarTabla(){
        modelo= (DefaultTableModel)tablaDetalleOrdenCompra.getModel();
        Object fila[] = new Object[3];
        deleteRows();
        for (int i=0; i < ordenCompra.getDetalleOrdenCompra().size();i++){
            fila[0]=ordenCompra.getDetalleOrdenCompra().get(i).getProducto().getIdProducto();
            fila[1]=ordenCompra.getDetalleOrdenCompra().get(i).getProducto().getNombre();
            fila[2]=ordenCompra.getDetalleOrdenCompra().get(i).getCantidad();            
            modelo.addRow(fila);
        }
        
    }
    private void deleteRows(){
        int rowCount = modelo.getRowCount();
        for (int i=rowCount-1 ; i>=0;i--){
            modelo.removeRow(i);
        }
    }
    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:

            if (txtCodigoProducto.getText().equals("")|| txtNombreProducto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Seleccione al menos un producto");
                //System.out.println("Error 1");
                return;
            }
        
    
            if (txtCantidad.getText().equals("")){
                //System.out.println("Error 2");
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad");
                return;
            }
        
        
        DetalleOrdenCompra detalle = new DetalleOrdenCompra();        
        detalle.setProducto(p);
        detalle.setCantidad(Integer.parseInt(txtCantidad.getText()));
        
        
        if( ! esta(p,ordenCompra.getDetalleOrdenCompra())){
            ordenCompra.getDetalleOrdenCompra().add(detalle);
            
            Object[]fila=new Object[3];
            modelo=(DefaultTableModel)tablaDetalleOrdenCompra.getModel();
            fila[0]=detalle.getProducto().getIdProducto();
            fila[1]=detalle.getProducto().getNombre();
            fila[2]=detalle.getCantidad();
            modelo.addRow(fila);
            ordenCompra.setCantidadTotalProducto(ordenCompra.getCantidadTotalProducto()+detalle.getCantidad());
            txtTotal.setText(String.valueOf(ordenCompra.getCantidadTotalProducto()));
        }else{
            JOptionPane.showMessageDialog(null, "Ya ingresó ese producto en la orden de compra");
            return;
        }
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your ohandling code here:
        try{
            int index = tablaDetalleOrdenCompra.getSelectedRow();
            txtCodigoProducto.setText(String.valueOf(ordenCompra.getDetalleOrdenCompra().get(index).getProducto().getIdProducto()));
            txtNombreProducto.setText(String.valueOf(ordenCompra.getDetalleOrdenCompra().get(index).getProducto().getNombre()));
            txtCantidad.setText(String.valueOf(ordenCompra.getDetalleOrdenCompra().get(index).getCantidad()));
            
            ordenCompra.setCantidadTotalProducto(ordenCompra.getCantidadTotalProducto()-ordenCompra.getDetalleOrdenCompra().get(index).getCantidad());
            
            p=ordenCompra.getDetalleOrdenCompra().get(index).getProducto();
            
            ordenCompra.getDetalleOrdenCompra().remove(index);
            modelo = (DefaultTableModel)tablaDetalleOrdenCompra.getModel();
            modelo.removeRow(index);
            
            
            txtTotal.setText(String.valueOf(ordenCompra.getCantidadTotalProducto()));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        try{
            int index = tablaDetalleOrdenCompra.getSelectedRow();
            ordenCompra.setCantidadTotalProducto(ordenCompra.getCantidadTotalProducto()-ordenCompra.getDetalleOrdenCompra().get(index).getCantidad());
            
            //p=ordenCompra.getDetalleOrdenCompra().get(index).getProducto();
            p=null;
            ordenCompra.getDetalleOrdenCompra().remove(index);
            modelo = (DefaultTableModel)tablaDetalleOrdenCompra.getModel();
            
            modelo.removeRow(index);
            
            txtTotal.setText(String.valueOf(ordenCompra.getCantidadTotalProducto()));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (ordenCompra.getDetalleOrdenCompra().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione al menos un producto");
            return;
        }
        try{
            ordenCompra.setFechaOrdenCompra(txtFechaOrden.getDate());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ingrese una fecha");
            return;
        }
        ordenCompra.setEstadoOrdenCompra(1);
        if (logicaNegocioOrdenCompra.registrarOrden(ordenCompra,frmPrincipal.usuario)){
            JOptionPane.showMessageDialog(null, "Se registro correctamente");
            estado(1);
            return;
        }else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar, ocurrió un error");
            estado(1);
            return;
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (ordenCompra.getEstadoOrdenCompra()==0){
            JOptionPane.showMessageDialog(null, "La orden de compra seleccionada ya ha sido atendida");
            return;
        }
        
        if(logicaNegocioOrdenCompra.actualizarOrden(ordenCompra,frmPrincipal.usuario)){
            JOptionPane.showMessageDialog(null, "Actualizado correctamente");
            return;
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo registrar, ocurrió un error");
            return;
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        estado(2);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        estado(3);
    }//GEN-LAST:event_btnEstadoActionPerformed
    private boolean esta(Producto p , ArrayList<DetalleOrdenCompra> detalle){
        for (int i=0; i<detalle.size();i++){
            if (p.getIdProducto()==detalle.get(i).getProducto().getIdProducto()){
                return true;
            }
        }
        return false;
    }
        private void estado(int i){
        switch (i){
            
            case 1:
                txtCodigo.setEnabled(false);
                txtCantidad.setEnabled(false);
                txtCodigoProducto.setEnabled(false);
                txtFechaOrden.setEnabled(false);
                txtNombreProducto.setEnabled(false);
                txtTotal.setEnabled(false);
                btnEstado.setEnabled(true);

                tablaDetalleOrdenCompra.setEnabled(false);
                btnRegistrar.setEnabled(false);
                btnBuscarOrdenDeCompra.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnGuardar.setEnabled(false);
                btnBuscarProducto.setEnabled(false);
                btnAnadir.setEnabled(false);
                btnModificar.setEnabled(false);
                btnQuitar.setEnabled(false);
                cboEstado.setEnabled(false);
                btnNuevo.setEnabled(true);
                break;
            case 2:
                txtCodigo.setEnabled(false);
                txtCantidad.setEnabled(true);
                txtCodigoProducto.setEnabled(true);
                txtFechaOrden.setEnabled(true);
                txtNombreProducto.setEnabled(true);
                txtTotal.setEnabled(false);
                btnEstado.setEnabled(true);

               // tablaDetalleOrdenCompra.setEnabled(true);
                btnRegistrar.setEnabled(true);
                btnBuscarOrdenDeCompra.setEnabled(false);
                btnCancelar.setEnabled(true);
                
                btnGuardar.setEnabled(false);
                btnBuscarProducto.setEnabled(true);
                btnAnadir.setEnabled(true);
                btnModificar.setEnabled(true);
                btnQuitar.setEnabled(true);
                cboEstado.setEnabled(false);
                //btnNuevo.setEnabled(false);
                break;
            case 3:
                txtCodigo.setEnabled(false);
                txtCantidad.setEnabled(false);
                txtCodigoProducto.setEnabled(false);
                txtFechaOrden.setEnabled(false);
                txtNombreProducto.setEnabled(false);
                txtTotal.setEnabled(false);
                btnEstado.setEnabled(false);
               // jPanel1.setEnabled(false);
                //tablaDetalleOrdenCompra.setEnabled(false);
                btnRegistrar.setEnabled(false);
                btnBuscarOrdenDeCompra.setEnabled(true);
                btnCancelar.setEnabled(true);
                
                btnGuardar.setEnabled(true);
                btnBuscarProducto.setEnabled(false);
                btnAnadir.setEnabled(false);
                btnModificar.setEnabled(false);
                btnQuitar.setEnabled(false);
                cboEstado.setEnabled(true);
                btnNuevo.setEnabled(false);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBuscarOrdenDeCompra;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalleOrdenCompra;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoProducto;
    private com.toedter.calendar.JDateChooser txtFechaOrden;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
