/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Vista_Menu;

import Vista.frmPrincipal;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;



/**
 *
 * @author Moises
 */
 enum Estado {Abierto,Cerrado,Nuevo}
public class frmCabecera extends javax.swing.JInternalFrame {
    private String nombreUsuario;
    private JDesktopPane padre;
    private frmMenuInicioLogistica frmMenuInicioLogistica;
    private frmMenuInicioSeguridad frmMenuInicioSeguridad;
    private frmMenuInicioAlmacenero frmMenuInicioAlmacenero;
    private Estado estado =Estado.Cerrado;
    /**
     * Creates new form frmCabecera
     */
    
        public Estado getEstado() {
        return estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public frmCabecera(JDesktopPane padre,String nombreUsuario) {
        
        initComponents();
        this.nombreUsuario=nombreUsuario;
        setNombreUsuario(nombreUsuario);
        lblNombreUsuario.setText(getNombreUsuario());
        this.padre=padre;
        inicializar();
          
    }
    private void inicializar(){
////PARA EL DISEÑO DEL PANEL cabecera 
//        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
//        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
        this.setLocation(0,0);
        //this.setBackground( new Color(165,198,231));
        this.setBackground( new Color(30, 67, 112));
        /// boton Menu
        btnMenu.setBounds(0,0,40, 34);
        ImageIcon img = new ImageIcon(getClass().getResource("/Imagenes/menu.png"));
        ImageIcon icono = new ImageIcon (img.getImage().
                getScaledInstance(btnMenu.getWidth(), btnMenu.getHeight(), Image.SCALE_SMOOTH));
        btnMenu.setIcon(icono);
        
        ///boton cerrar sesion
        btnCerrarSesion.setBounds(0,0,23,21);
        ImageIcon img2 = new ImageIcon(getClass().getResource("/Imagenes/power-button-off.png"));
        ImageIcon icono2 = new ImageIcon (img2.getImage().
                getScaledInstance(btnCerrarSesion.getWidth(), btnCerrarSesion.getHeight(), Image.SCALE_SMOOTH));
        btnCerrarSesion.setIcon(icono2);
        
        //Imagen perfil
        ImagenPerfil.setBounds(0,0,84,84);
        ImageIcon imgPerfil = new ImageIcon(getClass().getResource("/Imagenes/customer2.png"));
        ImageIcon iconoPerfil = new ImageIcon (imgPerfil.getImage().
                getScaledInstance(ImagenPerfil.getWidth(), ImagenPerfil.getHeight(), Image.SCALE_SMOOTH));
        ImagenPerfil.setIcon(iconoPerfil);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        ImagenPerfil = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1021, 111));
        setVisible(true);

        btnMenu.setBackground(new java.awt.Color(165, 198, 231));
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(165, 198, 231));
        btnCerrarSesion.setAlignmentX(701.0F);
        btnCerrarSesion.setAlignmentY(11.0F);
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(30, 67, 112));

        ImagenPerfil.setFocusable(false);

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre de usuario");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Perfil de usuario");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(ImagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ImagenPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 662, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        if (estado == Estado.Cerrado){//Si está abierto el menu
            switch (nombreUsuario) {
                case "log":
                     if (frmMenuInicioLogistica!=null){
                        frmMenuInicioLogistica.show();
                        estado=Estado.Abierto;
                    }else{
                        frmMenuInicioLogistica= new frmMenuInicioLogistica(this);
                        padre.add(frmMenuInicioLogistica);
                        frmMenuInicioLogistica.show();
                        estado=Estado.Abierto;
                    }
                    break;
                case "seg":
                    if (frmMenuInicioSeguridad!=null){
                        frmMenuInicioSeguridad.show();
                        estado=Estado.Abierto;
                    }else{
                        frmMenuInicioSeguridad= new frmMenuInicioSeguridad();
                        padre.add(frmMenuInicioSeguridad);
                        frmMenuInicioSeguridad.show();
                        estado=Estado.Abierto;
                    }
                    break;
                case "alm":
                    if (frmMenuInicioAlmacenero!=null){
                        frmMenuInicioAlmacenero.show();
                        estado=Estado.Abierto;
                    }else{
                        frmMenuInicioAlmacenero= new frmMenuInicioAlmacenero(this);
                        padre.add(frmMenuInicioAlmacenero);
                        frmMenuInicioAlmacenero.show();
                        estado=Estado.Abierto;
                    }
                    break;
                default :
                    if (frmMenuInicioAlmacenero!=null){
                        
                        
                        frmMenuInicioAlmacenero.show();
                        estado=Estado.Abierto;
                    }else{
                        frmMenuInicioAlmacenero= new frmMenuInicioAlmacenero(this);
                        padre.add(frmMenuInicioAlmacenero);
                        frmMenuInicioAlmacenero.show();
                        estado=Estado.Abierto;
                    }
                    break;
            }
        }else{
            switch (nombreUsuario) {
                case "log":
                    //padre.removeAll();
                    frmMenuInicioLogistica.hide();
                    estado=Estado.Cerrado;
                    break;
                case "seg":
                    frmMenuInicioSeguridad.hide();
                    estado=Estado.Cerrado;

                    break;
                case "alm":
                    frmMenuInicioAlmacenero.hide();
                    estado=Estado.Cerrado;

                    break;
                default :
                    frmMenuInicioAlmacenero.hide();  
                    estado=Estado.Cerrado;

                    break;
            }
        }
        
        
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenPerfil;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombreUsuario;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
