/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Vista_Menu;

import Vista.frmOrdenCompra;
import Vista.frmProductosAgotados;
import Vista.frmReportesGerenciales;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Moises
 */

public class frmMenuInicioLogistica extends javax.swing.JInternalFrame {
    private Estado estado ;
    private frmCabecera padre;
    frmProductosAgotados frmProductosAgotados;
    frmOrdenCompra frmOrdenCompra;
    frmReportesGerenciales frmReportesGerenciales;
    /**
     * Creates new form frmMenuInicioLogistica
     */
    public frmMenuInicioLogistica(frmCabecera padre) {
        initComponents();
        this.setLocation(0,111);
        //this.contenedorPadre = contenedorPadre;
        this.padre=padre;
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        estado=Estado.Abierto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrdenCompra = new javax.swing.JButton();
        btnProductosAgotados = new javax.swing.JButton();
        btnReportesGerenciales = new javax.swing.JButton();

        setBackground(new java.awt.Color(136, 161, 192));
        setBorder(null);

        btnOrdenCompra.setText("Orden de compra");
        btnOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenCompraActionPerformed(evt);
            }
        });

        btnProductosAgotados.setText("Productos agotados");
        btnProductosAgotados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosAgotadosActionPerformed(evt);
            }
        });

        btnReportesGerenciales.setText("Reportes gerenciales");
        btnReportesGerenciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesGerencialesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReportesGerenciales, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnProductosAgotados, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnOrdenCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnProductosAgotados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnReportesGerenciales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosAgotadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosAgotadosActionPerformed
        // TODO add your handling code here:
        if (frmProductosAgotados==null){
            frmProductosAgotados = new frmProductosAgotados();
           padre.getDesktopPane().add(frmProductosAgotados);
           frmProductosAgotados.show();
           this.hide();
   //        this.getDesktopPane().getTopLevelAncestor().getEstado();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }else{
            frmProductosAgotados.dispose();
             frmProductosAgotados = new frmProductosAgotados();
           padre.getDesktopPane().add(frmProductosAgotados);
           frmProductosAgotados.show();
           this.hide();
   //        this.getDesktopPane().getTopLevelAncestor().getEstado();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }
        if (frmOrdenCompra!=null) { 
            frmOrdenCompra.dispose() ;
            if(frmOrdenCompra.getFrmProductosAgotados()!=null){
                frmOrdenCompra.getFrmProductosAgotados().dispose();
            }
            
        }
        if (frmReportesGerenciales!=null)frmReportesGerenciales.dispose();
    }//GEN-LAST:event_btnProductosAgotadosActionPerformed

    private void btnOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenCompraActionPerformed
        // TODO add your handling code here:
        if (frmOrdenCompra==null){
            frmOrdenCompra = new frmOrdenCompra(padre);
           padre.getDesktopPane().add(frmOrdenCompra);
           frmOrdenCompra.show();
           this.hide();
           padre.setEstado(Estado.Cerrado);
           this.estado=Estado.Cerrado;
        }else{
           frmOrdenCompra.dispose();
           if (frmOrdenCompra.getFrmProductosAgotados()!=null){
               frmOrdenCompra.getFrmProductosAgotados().dispose();
           }
           frmOrdenCompra = new frmOrdenCompra(padre);
           
           padre.getDesktopPane().add(frmOrdenCompra);
           frmOrdenCompra.show();
           this.hide();
           padre.setEstado(Estado.Cerrado);
           this.estado=Estado.Cerrado;
        }
        if (frmProductosAgotados!=null) frmProductosAgotados.dispose() ;
        if (frmReportesGerenciales!=null)frmReportesGerenciales.dispose();
    }//GEN-LAST:event_btnOrdenCompraActionPerformed

    private void btnReportesGerencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesGerencialesActionPerformed
        // TODO add your handling code here:
        if (frmReportesGerenciales==null){
           frmReportesGerenciales = new frmReportesGerenciales();
           padre.getDesktopPane().add(frmReportesGerenciales);
           frmReportesGerenciales.show();
           this.hide();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }else{
           frmReportesGerenciales.dispose();
           frmReportesGerenciales = new frmReportesGerenciales();
           padre.getDesktopPane().add(frmReportesGerenciales);
           frmReportesGerenciales.show();
           this.hide();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }
        if (frmOrdenCompra!=null) { 
            frmOrdenCompra.dispose() ;
            if(frmOrdenCompra.getFrmProductosAgotados()!=null){
                frmOrdenCompra.getFrmProductosAgotados().dispose();
            }
            
        }
        if (frmProductosAgotados!=null)frmProductosAgotados.dispose();
    }//GEN-LAST:event_btnReportesGerencialesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdenCompra;
    private javax.swing.JButton btnProductosAgotados;
    private javax.swing.JButton btnReportesGerenciales;
    // End of variables declaration//GEN-END:variables
}
