/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Vista_Menu;

import Vista.frmGenerarGuiaRemision;
import Vista.frmOpcionesCuenta;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Moises
 */
public class frmMenuInicioSeguridad extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMenuInicioSeguridad
     */
    private Estado estado ;
    private frmCabecera padre;
    
    public frmMenuInicioSeguridad(frmCabecera padre) {
        initComponents();
        this.setLocation(0,111);
        this.padre = padre;
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCuentasAcceso = new javax.swing.JButton();

        setBackground(new java.awt.Color(136, 161, 192));
        setBorder(null);

        btnCuentasAcceso.setText("Cuentas de acceso");
        btnCuentasAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasAccesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCuentasAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnCuentasAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuentasAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasAccesoActionPerformed
        frmOpcionesCuenta frmOpc = new frmOpcionesCuenta(padre);
        padre.getDesktopPane().add(frmOpc);
        frmOpc.show();
        this.hide();
        padre.setEstado(Estado.Cerrado);
        this.estado=Estado.Cerrado;
    }//GEN-LAST:event_btnCuentasAccesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuentasAcceso;
    // End of variables declaration//GEN-END:variables
}
