/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Vista_Menu;

import Vista.frmOrdenCompra;
import Vista.frmProductosAgotados;
import Vista.frmReportesGerenciales;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Moises
 */

public class frmMenuInicioLogistica extends javax.swing.JInternalFrame {
    private Estado estado ;
    private frmCabecera padre;
    frmProductosAgotados frmProductosAgotados;
    frmOrdenCompra frmOrdenCompra;
    frmReportesGerenciales frmReportesGerenciales;
    /**
     * Creates new form frmMenuInicioLogistica
     */
    public frmMenuInicioLogistica(frmCabecera padre) {
        initComponents();
        this.setLocation(0,111);
        //this.contenedorPadre = contenedorPadre;
        this.padre=padre;
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        estado=Estado.Abierto;
    }
    void setColor(JPanel panel){
        panel.setBackground(new Color(30,67,112));
        //136,161,192
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(173,192,206));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProductosAgotados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelReportesGerenciales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelOrdenCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 67, 112));
        setBorder(null);

        panelProductosAgotados.setBackground(new java.awt.Color(173, 192, 206));
        panelProductosAgotados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProductosAgotadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProductosAgotadosMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelProductosAgotadosMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos agotados");

        javax.swing.GroupLayout panelProductosAgotadosLayout = new javax.swing.GroupLayout(panelProductosAgotados);
        panelProductosAgotados.setLayout(panelProductosAgotadosLayout);
        panelProductosAgotadosLayout.setHorizontalGroup(
            panelProductosAgotadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosAgotadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        panelProductosAgotadosLayout.setVerticalGroup(
            panelProductosAgotadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosAgotadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelReportesGerenciales.setBackground(new java.awt.Color(173, 192, 206));
        panelReportesGerenciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelReportesGerencialesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelReportesGerencialesMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelReportesGerencialesMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reportes gerenciales");

        javax.swing.GroupLayout panelReportesGerencialesLayout = new javax.swing.GroupLayout(panelReportesGerenciales);
        panelReportesGerenciales.setLayout(panelReportesGerencialesLayout);
        panelReportesGerencialesLayout.setHorizontalGroup(
            panelReportesGerencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReportesGerencialesLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelReportesGerencialesLayout.setVerticalGroup(
            panelReportesGerencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportesGerencialesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelOrdenCompra.setBackground(new java.awt.Color(173, 192, 206));
        panelOrdenCompra.setPreferredSize(new java.awt.Dimension(146, 43));
        panelOrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOrdenCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOrdenCompraMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelOrdenCompraMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orden de compra");

        javax.swing.GroupLayout panelOrdenCompraLayout = new javax.swing.GroupLayout(panelOrdenCompra);
        panelOrdenCompra.setLayout(panelOrdenCompraLayout);
        panelOrdenCompraLayout.setHorizontalGroup(
            panelOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrdenCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        panelOrdenCompraLayout.setVerticalGroup(
            panelOrdenCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdenCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProductosAgotados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelReportesGerenciales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelOrdenCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(panelOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelProductosAgotados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelReportesGerenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelOrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOrdenCompraMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (frmOrdenCompra==null){
           frmOrdenCompra = new frmOrdenCompra(padre);
           padre.getDesktopPane().add(frmOrdenCompra);
           frmOrdenCompra.show();
           this.hide();
           padre.setEstado(Estado.Cerrado);
           this.estado=Estado.Cerrado;
        }else{
           frmOrdenCompra.dispose();
           if (frmOrdenCompra.getFrmProductosAgotados()!=null){
               frmOrdenCompra.getFrmProductosAgotados().dispose();
           }
           frmOrdenCompra = new frmOrdenCompra(padre);
           
           padre.getDesktopPane().add(frmOrdenCompra);
           frmOrdenCompra.show();
           this.hide();
           padre.setEstado(Estado.Cerrado);
           this.estado=Estado.Cerrado;
        }
        if (frmProductosAgotados!=null) frmProductosAgotados.dispose() ;
        if (frmReportesGerenciales!=null)frmReportesGerenciales.dispose();
    }//GEN-LAST:event_panelOrdenCompraMouseClicked

    private void panelOrdenCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOrdenCompraMouseEntered
        // TODO add your handling code here:
        setColor(panelOrdenCompra);
        resetColor(panelProductosAgotados);
        resetColor(panelReportesGerenciales);
    }//GEN-LAST:event_panelOrdenCompraMouseEntered

    private void panelOrdenCompraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOrdenCompraMouseReleased
        // TODO add your handling code here:
        resetColor(panelProductosAgotados);
        resetColor(panelReportesGerenciales);
        resetColor(panelOrdenCompra);
    }//GEN-LAST:event_panelOrdenCompraMouseReleased

    private void panelProductosAgotadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductosAgotadosMouseClicked
        // TODO add your handling code here:
        if (frmProductosAgotados==null){
            frmProductosAgotados = new frmProductosAgotados();
           padre.getDesktopPane().add(frmProductosAgotados);
           frmProductosAgotados.show();
           this.hide();
   //        this.getDesktopPane().getTopLevelAncestor().getEstado();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }else{
            frmProductosAgotados.dispose();
             frmProductosAgotados = new frmProductosAgotados();
           padre.getDesktopPane().add(frmProductosAgotados);
           frmProductosAgotados.show();
           this.hide();
   //        this.getDesktopPane().getTopLevelAncestor().getEstado();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }
        if (frmOrdenCompra!=null) { 
            frmOrdenCompra.dispose() ;
            if(frmOrdenCompra.getFrmProductosAgotados()!=null){
                frmOrdenCompra.getFrmProductosAgotados().dispose();
            }
            
        }
        if (frmReportesGerenciales!=null)frmReportesGerenciales.dispose();
    }//GEN-LAST:event_panelProductosAgotadosMouseClicked

    private void panelProductosAgotadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductosAgotadosMouseEntered
        // TODO add your handling code here:
        setColor(panelProductosAgotados);
        resetColor(panelOrdenCompra);
        resetColor(panelReportesGerenciales);
    }//GEN-LAST:event_panelProductosAgotadosMouseEntered

    private void panelProductosAgotadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductosAgotadosMouseReleased
        // TODO add your handling code here:
        resetColor(panelProductosAgotados);
        resetColor(panelReportesGerenciales);
        resetColor(panelOrdenCompra);
    }//GEN-LAST:event_panelProductosAgotadosMouseReleased

    private void panelReportesGerencialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelReportesGerencialesMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (frmReportesGerenciales==null){
           frmReportesGerenciales = new frmReportesGerenciales();
           padre.getDesktopPane().add(frmReportesGerenciales);
           frmReportesGerenciales.show();
           this.hide();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }else{
           frmReportesGerenciales.dispose();
           frmReportesGerenciales = new frmReportesGerenciales();
           padre.getDesktopPane().add(frmReportesGerenciales);
           frmReportesGerenciales.show();
           this.hide();
           this.estado=Estado.Cerrado;
           padre.setEstado(Estado.Cerrado);
        }
        if (frmOrdenCompra!=null) { 
            frmOrdenCompra.dispose() ;
            if(frmOrdenCompra.getFrmProductosAgotados()!=null){
                frmOrdenCompra.getFrmProductosAgotados().dispose();
            }
            
        }
        if (frmProductosAgotados!=null)frmProductosAgotados.dispose();
    }//GEN-LAST:event_panelReportesGerencialesMouseClicked

    private void panelReportesGerencialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelReportesGerencialesMouseEntered
        // TODO add your handling code here:
        setColor(panelReportesGerenciales); 
        resetColor(panelProductosAgotados);
        resetColor(panelOrdenCompra);
    }//GEN-LAST:event_panelReportesGerencialesMouseEntered

    private void panelReportesGerencialesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelReportesGerencialesMouseReleased
        // TODO add your handling code here:
        resetColor(panelProductosAgotados);
        resetColor(panelReportesGerenciales);
        resetColor(panelOrdenCompra);
    }//GEN-LAST:event_panelReportesGerencialesMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelOrdenCompra;
    private javax.swing.JPanel panelProductosAgotados;
    private javax.swing.JPanel panelReportesGerenciales;
    // End of variables declaration//GEN-END:variables
}
